import { DateTime } from 'luxon';

const now = DateTime.now();

export const identifications = [
  {
    code: '0',
    description: 'CI POLICÍA FEDERAL',
    createdAt: now.plus({ minutes: 1 }).toString(),
    updatedAt: now.plus({ minutes: 1 }).toString(),
  },
  {
    code: '1',
    description: 'CI BUENOS AIRES',
    createdAt: now.plus({ minutes: 2 }).toString(),
    updatedAt: now.plus({ minutes: 2 }).toString(),
  },
  {
    code: '2',
    description: 'CI CATAMARCA',
    createdAt: now.plus({ minutes: 3 }).toString(),
    updatedAt: now.plus({ minutes: 3 }).toString(),
  },
  {
    code: '3',
    description: 'CI CÓRDOBA',
    createdAt: now.plus({ minutes: 4 }).toString(),
    updatedAt: now.plus({ minutes: 4 }).toString(),
  },
  {
    code: '4',
    description: 'CI CORRIENTES',
    createdAt: now.plus({ minutes: 5 }).toString(),
    updatedAt: now.plus({ minutes: 5 }).toString(),
  },
  {
    code: '5',
    description: 'CI ENTRE RÍOS',
    createdAt: now.plus({ minutes: 6 }).toString(),
    updatedAt: now.plus({ minutes: 6 }).toString(),
  },
  {
    code: '6',
    description: 'CI JUJUY',
    createdAt: now.plus({ minutes: 7 }).toString(),
    updatedAt: now.plus({ minutes: 7 }).toString(),
  },
  {
    code: '7',
    description: 'CI MENDOZA',
    createdAt: now.plus({ minutes: 8 }).toString(),
    updatedAt: now.plus({ minutes: 8 }).toString(),
  },
  {
    code: '8',
    description: 'CI LA RIOJA',
    createdAt: now.plus({ minutes: 9 }).toString(),
    updatedAt: now.plus({ minutes: 9 }).toString(),
  },
  {
    code: '9',
    description: 'CI SALTA',
    createdAt: now.plus({ minutes: 10 }).toString(),
    updatedAt: now.plus({ minutes: 10 }).toString(),
  },
  {
    code: '10',
    description: 'CI SAN JUAN',
    createdAt: now.plus({ minutes: 11 }).toString(),
    updatedAt: now.plus({ minutes: 11 }).toString(),
  },
  {
    code: '11',
    description: 'CI SAN LUIS',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: '12',
    description: 'CI SANTA FE',
    createdAt: now.plus({ minutes: 13 }).toString(),
    updatedAt: now.plus({ minutes: 13 }).toString(),
  },
  {
    code: '13',
    description: 'CI SANTIAGO DEL ESTERO',
    createdAt: now.plus({ minutes: 14 }).toString(),
    updatedAt: now.plus({ minutes: 14 }).toString(),
  },
  {
    code: '14',
    description: 'CI TUCUMÁN',
    createdAt: now.plus({ minutes: 15 }).toString(),
    updatedAt: now.plus({ minutes: 15 }).toString(),
  },
  {
    code: '16',
    description: 'CI CHACO',
    createdAt: now.plus({ minutes: 16 }).toString(),
    updatedAt: now.plus({ minutes: 16 }).toString(),
  },
  {
    code: '17',
    description: 'CI CHUBUT',
    createdAt: now.plus({ minutes: 17 }).toString(),
    updatedAt: now.plus({ minutes: 17 }).toString(),
  },
  {
    code: '18',
    description: 'CI FORMOSA',
    createdAt: now.plus({ minutes: 18 }).toString(),
    updatedAt: now.plus({ minutes: 18 }).toString(),
  },
  {
    code: '19',
    description: 'CI MISIONES',
    createdAt: now.plus({ minutes: 19 }).toString(),
    updatedAt: now.plus({ minutes: 19 }).toString(),
  },
  {
    code: '20',
    description: 'CI NEUQUÉN',
    createdAt: now.plus({ minutes: 20 }).toString(),
    updatedAt: now.plus({ minutes: 20 }).toString(),
  },
  {
    code: '21',
    description: 'CI LA PAMPA',
    createdAt: now.plus({ minutes: 21 }).toString(),
    updatedAt: now.plus({ minutes: 21 }).toString(),
  },
  {
    code: '22',
    description: 'CI RÍO NEGRO',
    createdAt: now.plus({ minutes: 22 }).toString(),
    updatedAt: now.plus({ minutes: 22 }).toString(),
  },
  {
    code: '23',
    description: 'CI SANTA CRUZ',
    createdAt: now.plus({ minutes: 23 }).toString(),
    updatedAt: now.plus({ minutes: 23 }).toString(),
  },
  {
    code: '24',
    description: 'CI TIERRA DEL FUEGO',
    createdAt: now.plus({ minutes: 24 }).toString(),
    updatedAt: now.plus({ minutes: 24 }).toString(),
  },
  {
    code: '80',
    description: 'CUIT',
    createdAt: now.plus({ minutes: 25 }).toString(),
    updatedAt: now.plus({ minutes: 25 }).toString(),
  },
  {
    code: '86',
    description: 'CUIL',
    createdAt: now.plus({ minutes: 26 }).toString(),
    updatedAt: now.plus({ minutes: 26 }).toString(),
  },
  {
    code: '87',
    description: 'CDI',
    createdAt: now.plus({ minutes: 27 }).toString(),
    updatedAt: now.plus({ minutes: 27 }).toString(),
  },
  {
    code: '89',
    description: 'LE',
    createdAt: now.plus({ minutes: 28 }).toString(),
    updatedAt: now.plus({ minutes: 28 }).toString(),
  },
  {
    code: '90',
    description: 'LC',
    createdAt: now.plus({ minutes: 29 }).toString(),
    updatedAt: now.plus({ minutes: 29 }).toString(),
  },
  {
    code: '91',
    description: 'CI EXTRANJERA',
    createdAt: now.plus({ minutes: 30 }).toString(),
    updatedAt: now.plus({ minutes: 30 }).toString(),
  },
  {
    code: '92',
    description: 'EN TRÁMITE',
    createdAt: now.plus({ minutes: 31 }).toString(),
    updatedAt: now.plus({ minutes: 31 }).toString(),
  },
  {
    code: '93',
    description: 'ACTA NACIMIENTO',
    createdAt: now.plus({ minutes: 32 }).toString(),
    updatedAt: now.plus({ minutes: 32 }).toString(),
  },
  {
    code: '94',
    description: 'PASAPORTE',
    createdAt: now.plus({ minutes: 33 }).toString(),
    updatedAt: now.plus({ minutes: 33 }).toString(),
  },
  {
    code: '95',
    description: 'CI BS. AS. RNP',
    createdAt: now.plus({ minutes: 34 }).toString(),
    updatedAt: now.plus({ minutes: 34 }).toString(),
  },
  {
    code: '96',
    description: 'DNI',
    createdAt: now.plus({ minutes: 35 }).toString(),
    updatedAt: now.plus({ minutes: 35 }).toString(),
  },
  {
    code: '99',
    description: 'SIN IDENTIFICAR/VENTA DIARIA',
    createdAt: now.plus({ minutes: 36 }).toString(),
    updatedAt: now.plus({ minutes: 36 }).toString(),
  },
  {
    code: '30',
    description: 'CERTIFICADO DE MIGRACIÓN',
    createdAt: now.plus({ minutes: 37 }).toString(),
    updatedAt: now.plus({ minutes: 37 }).toString(),
  },
  {
    code: '88',
    description: 'USADO POR ANSES PARA PADRÓN',
    createdAt: now.plus({ minutes: 38 }).toString(),
    updatedAt: now.plus({ minutes: 38 }).toString(),
  },
];
