import { MovementType } from '@prisma/client';
import { DateTime } from 'luxon';

const now = DateTime.now();

export const movements = [
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 2 }).toString(),
    updatedAt: now.plus({ seconds: 2 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 3 }).toString(),
    updatedAt: now.plus({ seconds: 3 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 4 }).toString(),
    updatedAt: now.plus({ seconds: 4 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 5 }).toString(),
    updatedAt: now.plus({ seconds: 5 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 6 }).toString(),
    updatedAt: now.plus({ seconds: 6 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 7 }).toString(),
    updatedAt: now.plus({ seconds: 7 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 8 }).toString(),
    updatedAt: now.plus({ seconds: 8 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 9 }).toString(),
    updatedAt: now.plus({ seconds: 9 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 10 }).toString(),
    updatedAt: now.plus({ seconds: 10 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 11 }).toString(),
    updatedAt: now.plus({ seconds: 11 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.CREATION,
    concept: 'Creación',
    userId: 1,
    paymentMethodId: 1,
    createdAt: now.plus({ seconds: 12 }).toString(),
    updatedAt: now.plus({ seconds: 12 }).toString(),
  },
  {
    amount: 28770,
    type: MovementType.OUT,
    concept: 'Compra',
    userId: 1,
    paymentMethodId: 1,
    purchaseId: 1,
    createdAt: now.plus({ seconds: 13 }).toString(),
    updatedAt: now.plus({ seconds: 13 }).toString(),
  },
  {
    amount: 9770.25,
    type: MovementType.IN,
    concept: 'Venta',
    userId: 1,
    clientId: 1,
    paymentMethodId: 2,
    cashMovementId: 1,
    createdAt: now.plus({ seconds: 14 }).toString(),
    updatedAt: now.plus({ seconds: 14 }).toString(),
  },
  {
    amount: 9770.25,
    type: MovementType.IN,
    concept: 'Venta',
    userId: 2,
    clientId: 2,
    paymentMethodId: 2,
    cashMovementId: 2,
    createdAt: now.plus({ seconds: 15 }).toString(),
    updatedAt: now.plus({ seconds: 15 }).toString(),
  },
  {
    amount: 1441.05,
    type: MovementType.OUT,
    concept: 'Baja/Pérdida',
    userId: 1,
    paymentMethodId: 1,
    dischargeId: 1,
    createdAt: now.plus({ seconds: 16 }).toString(),
    updatedAt: now.plus({ seconds: 16 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.TRANSFER_OUT,
    concept: 'Transferencia enviada',
    userId: 2,
    paymentMethodId: 1,
    transferId: 1,
    createdAt: now.plus({ seconds: 17 }).toString(),
    updatedAt: now.plus({ seconds: 17 }).toString(),
  },
  {
    amount: 0,
    type: MovementType.TRANSFER_IN,
    concept: 'Transferencia recibida',
    userId: 2,
    paymentMethodId: 1,
    transferId: 1,
    createdAt: now.plus({ seconds: 18 }).toString(),
    updatedAt: now.plus({ seconds: 18 }).toString(),
  },
];
