import { DateTime } from 'luxon';

const now = DateTime.now();

export const prices = [
  {
    price: 0,
    productId: 1,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    price: 640,
    productId: 1,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 2 }).toString(),
    updatedAt: now.plus({ seconds: 2 }).toString(),
  },
  {
    price: 0,
    productId: 1,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 3 }).toString(),
    updatedAt: now.plus({ seconds: 3 }).toString(),
  },
  {
    price: 655,
    productId: 1,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 4 }).toString(),
    updatedAt: now.plus({ seconds: 4 }).toString(),
  },
  {
    price: 0,
    productId: 1,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 5 }).toString(),
    updatedAt: now.plus({ seconds: 5 }).toString(),
  },
  // 2
  {
    price: 0,
    productId: 2,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 6 }).toString(),
    updatedAt: now.plus({ seconds: 6 }).toString(),
  },
  {
    price: 610,
    productId: 2,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 7 }).toString(),
    updatedAt: now.plus({ seconds: 7 }).toString(),
  },
  {
    price: 0,
    productId: 2,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 8 }).toString(),
    updatedAt: now.plus({ seconds: 8 }).toString(),
  },
  {
    price: 660,
    productId: 2,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 9 }).toString(),
    updatedAt: now.plus({ seconds: 9 }).toString(),
  },
  {
    price: 0,
    productId: 2,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 10 }).toString(),
    updatedAt: now.plus({ seconds: 10 }).toString(),
  },
  // 3
  {
    price: 0,
    productId: 3,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 11 }).toString(),
    updatedAt: now.plus({ seconds: 11 }).toString(),
  },
  {
    price: 142,
    productId: 3,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 12 }).toString(),
    updatedAt: now.plus({ seconds: 12 }).toString(),
  },
  {
    price: 0,
    productId: 3,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 13 }).toString(),
    updatedAt: now.plus({ seconds: 13 }).toString(),
  },
  {
    price: 152,
    productId: 3,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 14 }).toString(),
    updatedAt: now.plus({ seconds: 14 }).toString(),
  },
  {
    price: 0,
    productId: 3,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 15 }).toString(),
    updatedAt: now.plus({ seconds: 15 }).toString(),
  },
  // 4
  {
    price: 0,
    productId: 4,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 16 }).toString(),
    updatedAt: now.plus({ seconds: 16 }).toString(),
  },
  {
    price: 530,
    productId: 4,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 17 }).toString(),
    updatedAt: now.plus({ seconds: 17 }).toString(),
  },
  {
    price: 0,
    productId: 4,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 18 }).toString(),
    updatedAt: now.plus({ seconds: 18 }).toString(),
  },
  {
    price: 0,
    productId: 4,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 19 }).toString(),
    updatedAt: now.plus({ seconds: 19 }).toString(),
  },
  // 5
  {
    price: 638,
    productId: 5,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 20 }).toString(),
    updatedAt: now.plus({ seconds: 20 }).toString(),
  },
  {
    price: 0,
    productId: 5,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 21 }).toString(),
    updatedAt: now.plus({ seconds: 21 }).toString(),
  },
  {
    price: 0,
    productId: 5,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 22 }).toString(),
    updatedAt: now.plus({ seconds: 22 }).toString(),
  },
  {
    price: 439,
    productId: 5,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 23 }).toString(),
    updatedAt: now.plus({ seconds: 23 }).toString(),
  },
  {
    price: 413,
    productId: 5,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 24 }).toString(),
    updatedAt: now.plus({ seconds: 24 }).toString(),
  },
  {
    price: 0,
    productId: 5,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 25 }).toString(),
    updatedAt: now.plus({ seconds: 25 }).toString(),
  },
  // 6
  {
    price: 385,
    productId: 6,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 26 }).toString(),
    updatedAt: now.plus({ seconds: 26 }).toString(),
  },
  {
    price: 0,
    productId: 6,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 27 }).toString(),
    updatedAt: now.plus({ seconds: 27 }).toString(),
  },
  {
    price: 0,
    productId: 6,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 28 }).toString(),
    updatedAt: now.plus({ seconds: 28 }).toString(),
  },
  {
    price: 400,
    productId: 6,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 29 }).toString(),
    updatedAt: now.plus({ seconds: 29 }).toString(),
  },
  {
    price: 0,
    productId: 6,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 30 }).toString(),
    updatedAt: now.plus({ seconds: 30 }).toString(),
  },
  // 7
  {
    price: 0,
    productId: 7,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 31 }).toString(),
    updatedAt: now.plus({ seconds: 31 }).toString(),
  },
  {
    price: 755,
    productId: 7,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 32 }).toString(),
    updatedAt: now.plus({ seconds: 32 }).toString(),
  },
  {
    price: 0,
    productId: 7,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 33 }).toString(),
    updatedAt: now.plus({ seconds: 33 }).toString(),
  },
  {
    price: 800,
    productId: 7,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 34 }).toString(),
    updatedAt: now.plus({ seconds: 34 }).toString(),
  },
  {
    price: 0,
    productId: 7,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 35 }).toString(),
    updatedAt: now.plus({ seconds: 35 }).toString(),
  },
  // 8
  {
    price: 0,
    productId: 8,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 36 }).toString(),
    updatedAt: now.plus({ seconds: 36 }).toString(),
  },
  {
    price: 610,
    productId: 8,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 37 }).toString(),
    updatedAt: now.plus({ seconds: 37 }).toString(),
  },
  {
    price: 0,
    productId: 8,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 38 }).toString(),
    updatedAt: now.plus({ seconds: 38 }).toString(),
  },
  {
    price: 633,
    productId: 8,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 39 }).toString(),
    updatedAt: now.plus({ seconds: 39 }).toString(),
  },
  {
    price: 0,
    productId: 8,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 40 }).toString(),
    updatedAt: now.plus({ seconds: 40 }).toString(),
  },
  {
    price: 642,
    productId: 8,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 41 }).toString(),
    updatedAt: now.plus({ seconds: 41 }).toString(),
  },
  // 9
  {
    price: 0,
    productId: 9,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 42 }).toString(),
    updatedAt: now.plus({ seconds: 42 }).toString(),
  },
  {
    price: 855,
    productId: 9,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 43 }).toString(),
    updatedAt: now.plus({ seconds: 43 }).toString(),
  },
  {
    price: 0,
    productId: 9,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 44 }).toString(),
    updatedAt: now.plus({ seconds: 44 }).toString(),
  },
  {
    price: 0,
    productId: 9,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 45 }).toString(),
    updatedAt: now.plus({ seconds: 45 }).toString(),
  },
  // 10
  {
    price: 0,
    productId: 10,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 46 }).toString(),
    updatedAt: now.plus({ seconds: 46 }).toString(),
  },
  {
    price: 801,
    productId: 10,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 47 }).toString(),
    updatedAt: now.plus({ seconds: 47 }).toString(),
  },
  {
    price: 0,
    productId: 10,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 48 }).toString(),
    updatedAt: now.plus({ seconds: 48 }).toString(),
  },
  {
    price: 855.5,
    productId: 10,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 49 }).toString(),
    updatedAt: now.plus({ seconds: 49 }).toString(),
  },
  {
    price: 0,
    productId: 10,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 50 }).toString(),
    updatedAt: now.plus({ seconds: 50 }).toString(),
  },
  // 11
  {
    price: 0,
    productId: 11,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 51 }).toString(),
    updatedAt: now.plus({ seconds: 51 }).toString(),
  },
  {
    price: 800.5,
    productId: 11,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 52 }).toString(),
    updatedAt: now.plus({ seconds: 52 }).toString(),
  },
  {
    price: 790.5,
    productId: 11,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 53 }).toString(),
    updatedAt: now.plus({ seconds: 53 }).toString(),
  },
  {
    price: 0,
    productId: 11,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 54 }).toString(),
    updatedAt: now.plus({ seconds: 54 }).toString(),
  },
  {
    price: 0,
    productId: 11,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 55 }).toString(),
    updatedAt: now.plus({ seconds: 55 }).toString(),
  },
  // 12
  {
    price: 0,
    productId: 12,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 56 }).toString(),
    updatedAt: now.plus({ seconds: 56 }).toString(),
  },
  {
    price: 988.35,
    productId: 12,
    pricelistId: 1,
    createdAt: now.plus({ seconds: 57 }).toString(),
    updatedAt: now.plus({ seconds: 57 }).toString(),
  },
  {
    price: 0,
    productId: 12,
    pricelistId: 2,
    createdAt: now.plus({ seconds: 58 }).toString(),
    updatedAt: now.plus({ seconds: 58 }).toString(),
  },
  {
    price: 0,
    productId: 12,
    pricelistId: 3,
    createdAt: now.plus({ seconds: 59 }).toString(),
    updatedAt: now.plus({ seconds: 59 }).toString(),
  },
];
