import { DateTime } from 'luxon';

const now = DateTime.now();

export const prices = [
  {
    price: 630,
    productId: 1,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 1 }).toString(),
    updatedAt: now.plus({ minutes: 1 }).toString(),
  },
  {
    price: 632,
    productId: 1,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 2 }).toString(),
    updatedAt: now.plus({ minutes: 2 }).toString(),
  },
  {
    price: 640,
    productId: 1,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 3 }).toString(),
    updatedAt: now.plus({ minutes: 3 }).toString(),
  },
  {
    price: 650,
    productId: 1,
    pricelistId: 2,
    createdAt: now.plus({ minutes: 4 }).toString(),
    updatedAt: now.plus({ minutes: 4 }).toString(),
  },
  {
    price: 655,
    productId: 1,
    pricelistId: 2,
    createdAt: now.plus({ minutes: 5 }).toString(),
    updatedAt: now.plus({ minutes: 5 }).toString(),
  },
  {
    price: 610,
    productId: 2,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 6 }).toString(),
    updatedAt: now.plus({ minutes: 6 }).toString(),
  },
  {
    price: 660,
    productId: 2,
    pricelistId: 2,
    createdAt: now.plus({ minutes: 7 }).toString(),
    updatedAt: now.plus({ minutes: 7 }).toString(),
  },
  {
    price: 0,
    productId: 2,
    pricelistId: 3,
    createdAt: now.plus({ minutes: 8 }).toString(),
    updatedAt: now.plus({ minutes: 8 }).toString(),
  },
  {
    price: 138,
    productId: 3,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 9 }).toString(),
    updatedAt: now.plus({ minutes: 9 }).toString(),
  },
  {
    price: 142,
    productId: 3,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 10 }).toString(),
    updatedAt: now.plus({ minutes: 10 }).toString(),
  },
  {
    price: 152,
    productId: 3,
    pricelistId: 2,
    createdAt: now.plus({ minutes: 11 }).toString(),
    updatedAt: now.plus({ minutes: 11 }).toString(),
  },
  {
    price: 530,
    productId: 4,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    price: 638,
    productId: 5,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 13 }).toString(),
    updatedAt: now.plus({ minutes: 13 }).toString(),
  },
  {
    price: 439,
    productId: 5,
    pricelistId: 2,
    createdAt: now.plus({ minutes: 14 }).toString(),
    updatedAt: now.plus({ minutes: 14 }).toString(),
  },
  {
    price: 385,
    productId: 6,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 15 }).toString(),
    updatedAt: now.plus({ minutes: 15 }).toString(),
  },
  {
    price: 400,
    productId: 6,
    pricelistId: 2,
    createdAt: now.plus({ minutes: 16 }).toString(),
    updatedAt: now.plus({ minutes: 16 }).toString(),
  },
  {
    price: 413,
    productId: 5,
    pricelistId: 3,
    createdAt: now.plus({ minutes: 17 }).toString(),
    updatedAt: now.plus({ minutes: 17 }).toString(),
  },
  {
    price: 755,
    productId: 7,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 18 }).toString(),
    updatedAt: now.plus({ minutes: 18 }).toString(),
  },
  {
    price: 800,
    productId: 7,
    pricelistId: 2,
    createdAt: now.plus({ minutes: 19 }).toString(),
    updatedAt: now.plus({ minutes: 19 }).toString(),
  },
  {
    price: 610,
    productId: 8,
    pricelistId: 1,
    createdAt: now.plus({ minutes: 20 }).toString(),
    updatedAt: now.plus({ minutes: 20 }).toString(),
  },
  {
    price: 633,
    productId: 8,
    pricelistId: 2,
    createdAt: now.plus({ minutes: 21 }).toString(),
    updatedAt: now.plus({ minutes: 21 }).toString(),
  },
  {
    price: 642,
    productId: 8,
    pricelistId: 3,
    createdAt: now.plus({ minutes: 22 }).toString(),
    updatedAt: now.plus({ minutes: 22 }).toString(),
  },
];
