import { StatusType } from '@prisma/client';
import { DateTime } from 'luxon';

const now = DateTime.now();

export const products = [
  {
    code: 'tom',
    name: 'Tomate Redondo',
    barcode: '0123456789012',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    description: '',
    createdAt: now.plus({ minutes: 1 }).toString(),
    updatedAt: now.plus({ minutes: 1 }).toString(),
  },
  {
    code: 'maple',
    name: 'Huevos (x36)',
    barcode: '1234567890123',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 4,
    unitId: 1,
    description: 'Maple de huevos',
    createdAt: now.plus({ minutes: 2 }).toString(),
    updatedAt: now.plus({ minutes: 2 }).toString(),
  },
  {
    code: 'leche',
    name: 'Leche Largavida',
    barcode: '2345678901234',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 4,
    unitId: 1,
    description: '',
    createdAt: now.plus({ minutes: 3 }).toString(),
    updatedAt: now.plus({ minutes: 3 }).toString(),
  },
  {
    code: 'manz',
    name: 'Manzana Roja',
    barcode: '3456789012345',
    status: StatusType.DISABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 2,
    unitId: 2,
    description: '',
    createdAt: now.plus({ minutes: 4 }).toString(),
    updatedAt: now.plus({ minutes: 4 }).toString(),
  },
  {
    code: 'manzpre',
    name: 'Manzana Roja Premiun',
    barcode: '4567890123456',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 2,
    unitId: 2,
    description: 'Manzana roja de primera calidad',
    createdAt: now.plus({ minutes: 5 }).toString(),
    updatedAt: now.plus({ minutes: 5 }).toString(),
  },
  {
    code: 'cebola',
    name: 'Cebolla Suelta',
    barcode: '5678901234567',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    description: '',
    createdAt: now.plus({ minutes: 6 }).toString(),
    updatedAt: now.plus({ minutes: 6 }).toString(),
  },
  {
    code: 'carbon',
    name: 'Bolsa de Carbón (5 Kg.)',
    barcode: '6789012345678',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 1,
    unitId: 2,
    description: '',
    createdAt: now.plus({ minutes: 7 }).toString(),
    updatedAt: now.plus({ minutes: 7 }).toString(),
  },
  {
    code: 'rucu',
    name: 'Rúcula',
    barcode: '7890123456789',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    description: '',
    createdAt: now.plus({ minutes: 8 }).toString(),
    updatedAt: now.plus({ minutes: 8 }).toString(),
  },
];
