import { StatusType } from '@prisma/client';
import { DateTime } from 'luxon';

const now = DateTime.now();

export const products = [
  {
    code: 'tom',
    name: 'Tomate Redondo',
    barcode: '0123456789012',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.ENABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 3,
    description: '',
    createdAt: now.plus({ minutes: 1 }).toString(),
    updatedAt: now.plus({ minutes: 1 }).toString(),
  },
  {
    code: 'maple',
    name: 'Huevos (x36)',
    barcode: '1234567890123',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 4,
    unitId: 1,
    ivaConditionId: 5,
    description: 'Maple de huevos',
    createdAt: now.plus({ minutes: 2 }).toString(),
    updatedAt: now.plus({ minutes: 2 }).toString(),
  },
  {
    code: 'leche',
    name: 'Leche Largavida',
    barcode: '2345678901234',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 4,
    unitId: 1,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 3 }).toString(),
    updatedAt: now.plus({ minutes: 3 }).toString(),
  },
  {
    code: 'manz',
    name: 'Manzana Roja',
    barcode: '3456789012345',
    status: StatusType.DISABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 2,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 4 }).toString(),
    updatedAt: now.plus({ minutes: 4 }).toString(),
  },
  {
    code: 'manzpre',
    name: 'Manzana Roja Premiun',
    barcode: '4567890123456',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 2,
    unitId: 2,
    ivaConditionId: 6,
    description: 'Manzana roja de primera calidad',
    createdAt: now.plus({ minutes: 5 }).toString(),
    updatedAt: now.plus({ minutes: 5 }).toString(),
  },
  {
    code: 'cebola',
    name: 'Cebolla Suelta',
    barcode: '5678901234567',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 6 }).toString(),
    updatedAt: now.plus({ minutes: 6 }).toString(),
  },
  {
    code: 'carbon',
    name: 'Bolsa de Carbón (5 Kg.)',
    barcode: '6789012345678',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 1,
    unitId: 1,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 7 }).toString(),
    updatedAt: now.plus({ minutes: 7 }).toString(),
  },
  {
    code: 'rucu',
    name: 'Rúcula',
    barcode: '7890123456789',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 8 }).toString(),
    updatedAt: now.plus({ minutes: 8 }).toString(),
  },
  {
    code: 'Beren',
    name: 'Berenjegas',
    barcode: '7854123456789',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 9 }).toString(),
    updatedAt: now.plus({ minutes: 9 }).toString(),
  },
  {
    code: 'Lim',
    name: 'Limón',
    barcode: '7854123477789',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 10 }).toString(),
    updatedAt: now.plus({ minutes: 10 }).toString(),
  },
  {
    code: 'Zapac',
    name: 'Zapallo Criollo',
    barcode: '7952123477789',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 11 }).toString(),
    updatedAt: now.plus({ minutes: 11 }).toString(),
  },
  {
    code: 'Pera',
    name: 'Pera',
    barcode: '7952123466789',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'A',
    name: 'A',
    barcode: '7952123466710',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'B',
    name: 'B',
    barcode: '7952123466711',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'C',
    name: 'C',
    barcode: '7952123466712',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'D',
    name: 'D',
    barcode: '7952123466713',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'E',
    name: 'E',
    barcode: '7952123466714',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'F',
    name: 'F',
    barcode: '7952123466714',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'G',
    name: 'G',
    barcode: '7952123466715',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'H',
    name: 'H',
    barcode: '7952123466716',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'I',
    name: 'I',
    barcode: '7952123466717',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'J',
    name: 'J',
    barcode: '7952123466717',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'K',
    name: 'K',
    barcode: '7952123466718',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'L',
    name: 'L',
    barcode: '7952123466719',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'M',
    name: 'M',
    barcode: '7952123466720',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    code: 'N',
    name: 'N',
    barcode: '7952123466721',
    status: StatusType.ENABLED,
    allownegativestock: StatusType.DISABLED,
    categoryId: 3,
    unitId: 2,
    ivaConditionId: 6,
    description: '',
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
];
