import { DateTime } from 'luxon';

const now = DateTime.now();

export const stockDetails = [
  {
    productId: 1,
    warehouseId: 1,
    stock: 0,
    movementId: 1,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 2,
    stock: 0,
    movementId: 1,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 3,
    stock: 0,
    movementId: 1,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 0,
    movementId: 2,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 2,
    stock: 0,
    movementId: 2,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 3,
    stock: 0,
    movementId: 2,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 3,
    warehouseId: 1,
    stock: 0,
    movementId: 3,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 3,
    warehouseId: 2,
    stock: 0,
    movementId: 3,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 3,
    warehouseId: 3,
    stock: 0,
    movementId: 3,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 4,
    warehouseId: 1,
    stock: 0,
    movementId: 4,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 4,
    warehouseId: 2,
    stock: 0,
    movementId: 4,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 4,
    warehouseId: 3,
    stock: 0,
    movementId: 4,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 5,
    warehouseId: 1,
    stock: 0,
    movementId: 5,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 5,
    warehouseId: 2,
    stock: 0,
    movementId: 5,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 5,
    warehouseId: 3,
    stock: 0,
    movementId: 5,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 6,
    warehouseId: 1,
    stock: 0,
    movementId: 6,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 6,
    warehouseId: 2,
    stock: 0,
    movementId: 6,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 6,
    warehouseId: 3,
    stock: 0,
    movementId: 6,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 7,
    warehouseId: 1,
    stock: 0,
    movementId: 7,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 7,
    warehouseId: 2,
    stock: 0,
    movementId: 7,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 7,
    warehouseId: 3,
    stock: 0,
    movementId: 7,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 8,
    warehouseId: 1,
    stock: 0,
    movementId: 8,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 8,
    warehouseId: 2,
    stock: 0,
    movementId: 8,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 8,
    warehouseId: 3,
    stock: 0,
    movementId: 8,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 9,
    warehouseId: 1,
    stock: 0,
    movementId: 9,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 9,
    warehouseId: 2,
    stock: 0,
    movementId: 9,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 9,
    warehouseId: 3,
    stock: 0,
    movementId: 9,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 10,
    warehouseId: 1,
    stock: 0,
    movementId: 10,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 10,
    warehouseId: 2,
    stock: 0,
    movementId: 10,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 10,
    warehouseId: 3,
    stock: 0,
    movementId: 10,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 11,
    warehouseId: 1,
    stock: 0,
    movementId: 11,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 11,
    warehouseId: 2,
    stock: 0,
    movementId: 11,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 11,
    warehouseId: 3,
    stock: 0,
    movementId: 11,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 12,
    warehouseId: 1,
    stock: 0,
    movementId: 12,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 12,
    warehouseId: 2,
    stock: 0,
    movementId: 12,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 12,
    warehouseId: 3,
    stock: 0,
    movementId: 12,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 12,
    warehouseId: 3,
    stock: 0,
    movementId: 12,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 40,
    movementId: 13,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 12,
    movementId: 13,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 3,
    warehouseId: 1,
    stock: 35,
    movementId: 13,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 30,
    movementId: 14,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 7,
    movementId: 14,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 20,
    movementId: 15,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 2,
    movementId: 15,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 17,
    movementId: 16,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 12,
    movementId: 17,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 1,
    movementId: 17,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 2,
    stock: 5,
    movementId: 18,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 2,
    stock: 1,
    movementId: 18,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
];
