import { DateTime } from 'luxon';

const now = DateTime.now();

export const stocks = [
  {
    stock: 100,
    prevstock: 0,
    prevdate: new Date(),
    productId: 1,
    warehouseId: 1,
    createdAt: now.plus({ minutes: 1 }).toString(),
    updatedAt: now.plus({ minutes: 1 }).toString(),
  },
  {
    stock: 150,
    prevstock: 100,
    prevdate: new Date(),
    productId: 1,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 2 }).toString(),
    updatedAt: now.plus({ minutes: 2 }).toString(),
  },
  {
    stock: 25,
    prevstock: 0,
    prevdate: new Date(),
    productId: 2,
    warehouseId: 1,
    createdAt: now.plus({ minutes: 3 }).toString(),
    updatedAt: now.plus({ minutes: 3 }).toString(),
  },
  {
    stock: 30,
    prevstock: 25,
    prevdate: new Date(),
    productId: 2,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 4 }).toString(),
    updatedAt: now.plus({ minutes: 4 }).toString(),
  },
  {
    stock: 32,
    prevstock: 0,
    prevdate: new Date(),
    productId: 3,
    warehouseId: 1,
    createdAt: now.plus({ minutes: 5 }).toString(),
    updatedAt: now.plus({ minutes: 5 }).toString(),
  },
  {
    stock: 57,
    prevstock: 32,
    prevdate: new Date(),
    productId: 3,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 6 }).toString(),
    updatedAt: now.plus({ minutes: 6 }).toString(),
  },
  {
    stock: 60,
    prevstock: 0,
    prevdate: new Date(),
    productId: 4,
    warehouseId: 1,
    createdAt: now.plus({ minutes: 7 }).toString(),
    updatedAt: now.plus({ minutes: 7 }).toString(),
  },
  {
    stock: 55,
    prevstock: 60,
    prevdate: new Date(),
    productId: 4,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 8 }).toString(),
    updatedAt: now.plus({ minutes: 8 }).toString(),
  },
  {
    stock: 30,
    prevstock: 0,
    prevdate: new Date(),
    productId: 5,
    warehouseId: 1,
    createdAt: now.plus({ minutes: 9 }).toString(),
    updatedAt: now.plus({ minutes: 9 }).toString(),
  },
  {
    stock: 10,
    prevstock: 30,
    prevdate: new Date(),
    productId: 5,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 10 }).toString(),
    updatedAt: now.plus({ minutes: 10 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 6,
    warehouseId: 1,
    createdAt: now.plus({ minutes: 11 }).toString(),
    updatedAt: now.plus({ minutes: 11 }).toString(),
  },
  {
    stock: 33,
    prevstock: 0,
    prevdate: new Date(),
    productId: 6,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 12 }).toString(),
    updatedAt: now.plus({ minutes: 12 }).toString(),
  },
  {
    stock: 10,
    prevstock: 0,
    prevdate: new Date(),
    productId: 7,
    warehouseId: 1,
    createdAt: now.plus({ minutes: 13 }).toString(),
    updatedAt: now.plus({ minutes: 13 }).toString(),
  },
  {
    stock: 7,
    prevstock: 10,
    prevdate: new Date(),
    productId: 7,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 1 }).toString(),
    updatedAt: now.plus({ minutes: 1 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 8,
    warehouseId: 1,
    createdAt: now.plus({ minutes: 14 }).toString(),
    updatedAt: now.plus({ minutes: 14 }).toString(),
  },
  {
    stock: 40,
    prevstock: 0,
    prevdate: new Date(),
    productId: 8,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 15 }).toString(),
    updatedAt: now.plus({ minutes: 15 }).toString(),
  },
  // DRIVERS
  {
    stock: 10,
    prevstock: 0,
    prevdate: new Date(),
    productId: 1,
    warehouseId: 3,
    createdAt: now.plus({ minutes: 16 }).toString(),
    updatedAt: now.plus({ minutes: 16 }).toString(),
  },
  {
    stock: 12,
    prevstock: 0,
    prevdate: new Date(),
    productId: 2,
    warehouseId: 3,
    createdAt: now.plus({ minutes: 17 }).toString(),
    updatedAt: now.plus({ minutes: 17 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 3,
    warehouseId: 3,
    createdAt: now.plus({ minutes: 18 }).toString(),
    updatedAt: now.plus({ minutes: 18 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 4,
    warehouseId: 3,
    createdAt: now.plus({ minutes: 19 }).toString(),
    updatedAt: now.plus({ minutes: 19 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 6,
    warehouseId: 3,
    createdAt: now.plus({ minutes: 22 }).toString(),
    updatedAt: now.plus({ minutes: 22 }).toString(),
  },
  {
    stock: 33,
    prevstock: 0,
    prevdate: new Date(),
    productId: 9,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 21 }).toString(),
    updatedAt: now.plus({ minutes: 21 }).toString(),
  },
  {
    stock: 50,
    prevstock: 0,
    prevdate: new Date(),
    productId: 10,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 22 }).toString(),
    updatedAt: now.plus({ minutes: 22 }).toString(),
  },
  {
    stock: 19,
    prevstock: 0,
    prevdate: new Date(),
    productId: 12,
    warehouseId: 2,
    createdAt: now.plus({ minutes: 23 }).toString(),
    updatedAt: now.plus({ minutes: 23 }).toString(),
  },
];
