import { DateTime } from 'luxon';

const now = DateTime.now();

export const stocks = [
  {
    stock: 12,
    prevstock: 17,
    prevdate: new Date(),
    productId: 1,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    stock: 5,
    prevstock: 0,
    prevdate: new Date(),
    productId: 1,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 2 }).toString(),
    updatedAt: now.plus({ seconds: 2 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 1,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 3 }).toString(),
    updatedAt: now.plus({ seconds: 3 }).toString(),
  },
  {
    stock: 1,
    prevstock: 2,
    prevdate: new Date(),
    productId: 2,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 4 }).toString(),
    updatedAt: now.plus({ seconds: 4 }).toString(),
  },
  {
    stock: 1,
    prevstock: 0,
    prevdate: new Date(),
    productId: 2,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 5 }).toString(),
    updatedAt: now.plus({ seconds: 5 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 2,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 6 }).toString(),
    updatedAt: now.plus({ seconds: 6 }).toString(),
  },
  {
    stock: 35,
    prevstock: 0,
    prevdate: new Date(),
    productId: 3,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 7 }).toString(),
    updatedAt: now.plus({ seconds: 7 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 3,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 8 }).toString(),
    updatedAt: now.plus({ seconds: 8 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 3,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 9 }).toString(),
    updatedAt: now.plus({ seconds: 9 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 4,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 10 }).toString(),
    updatedAt: now.plus({ seconds: 10 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 4,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 11 }).toString(),
    updatedAt: now.plus({ seconds: 11 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 4,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 12 }).toString(),
    updatedAt: now.plus({ seconds: 12 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 5,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 13 }).toString(),
    updatedAt: now.plus({ seconds: 13 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 5,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 14 }).toString(),
    updatedAt: now.plus({ seconds: 14 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 5,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 15 }).toString(),
    updatedAt: now.plus({ seconds: 15 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 6,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 16 }).toString(),
    updatedAt: now.plus({ seconds: 16 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 6,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 17 }).toString(),
    updatedAt: now.plus({ seconds: 17 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 6,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 18 }).toString(),
    updatedAt: now.plus({ seconds: 18 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 7,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 19 }).toString(),
    updatedAt: now.plus({ seconds: 19 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 7,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 20 }).toString(),
    updatedAt: now.plus({ seconds: 20 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 7,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 21 }).toString(),
    updatedAt: now.plus({ seconds: 21 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 8,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 22 }).toString(),
    updatedAt: now.plus({ seconds: 22 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 8,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 23 }).toString(),
    updatedAt: now.plus({ seconds: 23 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 8,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 24 }).toString(),
    updatedAt: now.plus({ seconds: 24 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 9,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 25 }).toString(),
    updatedAt: now.plus({ seconds: 25 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 9,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 26 }).toString(),
    updatedAt: now.plus({ seconds: 26 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 9,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 27 }).toString(),
    updatedAt: now.plus({ seconds: 27 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 10,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 28 }).toString(),
    updatedAt: now.plus({ seconds: 28 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 10,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 29 }).toString(),
    updatedAt: now.plus({ seconds: 29 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 10,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 30 }).toString(),
    updatedAt: now.plus({ seconds: 30 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 11,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 31 }).toString(),
    updatedAt: now.plus({ seconds: 31 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 11,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 32 }).toString(),
    updatedAt: now.plus({ seconds: 32 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 11,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 33 }).toString(),
    updatedAt: now.plus({ seconds: 33 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 12,
    warehouseId: 1,
    createdAt: now.plus({ seconds: 34 }).toString(),
    updatedAt: now.plus({ seconds: 34 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 12,
    warehouseId: 2,
    createdAt: now.plus({ seconds: 35 }).toString(),
    updatedAt: now.plus({ seconds: 35 }).toString(),
  },
  {
    stock: 0,
    prevstock: 0,
    prevdate: new Date(),
    productId: 12,
    warehouseId: 3,
    createdAt: now.plus({ seconds: 36 }).toString(),
    updatedAt: now.plus({ seconds: 36 }).toString(),
  },
];
