import { DateTime } from 'luxon';

const now = DateTime.now();

export const stockDetails = [
  {
    productId: 1,
    warehouseId: 1,
    stock: 0,
    movementId: 1,
    createdAt: now.plus({ seconds: 1 }).toString(),
    updatedAt: now.plus({ seconds: 1 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 2,
    stock: 0,
    movementId: 1,
    createdAt: now.plus({ seconds: 2 }).toString(),
    updatedAt: now.plus({ seconds: 2 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 3,
    stock: 0,
    movementId: 1,
    createdAt: now.plus({ seconds: 3 }).toString(),
    updatedAt: now.plus({ seconds: 3 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 0,
    movementId: 2,
    createdAt: now.plus({ seconds: 4 }).toString(),
    updatedAt: now.plus({ seconds: 4 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 2,
    stock: 0,
    movementId: 2,
    createdAt: now.plus({ seconds: 5 }).toString(),
    updatedAt: now.plus({ seconds: 5 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 3,
    stock: 0,
    movementId: 2,
    createdAt: now.plus({ seconds: 6 }).toString(),
    updatedAt: now.plus({ seconds: 6 }).toString(),
  },
  {
    productId: 3,
    warehouseId: 1,
    stock: 0,
    movementId: 3,
    createdAt: now.plus({ seconds: 7 }).toString(),
    updatedAt: now.plus({ seconds: 7 }).toString(),
  },
  {
    productId: 3,
    warehouseId: 2,
    stock: 0,
    movementId: 3,
    createdAt: now.plus({ seconds: 8 }).toString(),
    updatedAt: now.plus({ seconds: 8 }).toString(),
  },
  {
    productId: 3,
    warehouseId: 3,
    stock: 0,
    movementId: 3,
    createdAt: now.plus({ seconds: 9 }).toString(),
    updatedAt: now.plus({ seconds: 9 }).toString(),
  },
  {
    productId: 4,
    warehouseId: 1,
    stock: 0,
    movementId: 4,
    createdAt: now.plus({ seconds: 10 }).toString(),
    updatedAt: now.plus({ seconds: 10 }).toString(),
  },
  {
    productId: 4,
    warehouseId: 2,
    stock: 0,
    movementId: 4,
    createdAt: now.plus({ seconds: 11 }).toString(),
    updatedAt: now.plus({ seconds: 11 }).toString(),
  },
  {
    productId: 4,
    warehouseId: 3,
    stock: 0,
    movementId: 4,
    createdAt: now.plus({ seconds: 12 }).toString(),
    updatedAt: now.plus({ seconds: 12 }).toString(),
  },
  {
    productId: 5,
    warehouseId: 1,
    stock: 0,
    movementId: 5,
    createdAt: now.plus({ seconds: 13 }).toString(),
    updatedAt: now.plus({ seconds: 13 }).toString(),
  },
  {
    productId: 5,
    warehouseId: 2,
    stock: 0,
    movementId: 5,
    createdAt: now.plus({ seconds: 14 }).toString(),
    updatedAt: now.plus({ seconds: 14 }).toString(),
  },
  {
    productId: 5,
    warehouseId: 3,
    stock: 0,
    movementId: 5,
    createdAt: now.plus({ seconds: 15 }).toString(),
    updatedAt: now.plus({ seconds: 15 }).toString(),
  },
  {
    productId: 6,
    warehouseId: 1,
    stock: 0,
    movementId: 6,
    createdAt: now.plus({ seconds: 16 }).toString(),
    updatedAt: now.plus({ seconds: 16 }).toString(),
  },
  {
    productId: 6,
    warehouseId: 2,
    stock: 0,
    movementId: 6,
    createdAt: now.plus({ seconds: 17 }).toString(),
    updatedAt: now.plus({ seconds: 17 }).toString(),
  },
  {
    productId: 6,
    warehouseId: 3,
    stock: 0,
    movementId: 6,
    createdAt: now.plus({ seconds: 18 }).toString(),
    updatedAt: now.plus({ seconds: 18 }).toString(),
  },
  {
    productId: 7,
    warehouseId: 1,
    stock: 0,
    movementId: 7,
    createdAt: now.plus({ seconds: 19 }).toString(),
    updatedAt: now.plus({ seconds: 19 }).toString(),
  },
  {
    productId: 7,
    warehouseId: 2,
    stock: 0,
    movementId: 7,
    createdAt: now.plus({ seconds: 20 }).toString(),
    updatedAt: now.plus({ seconds: 20 }).toString(),
  },
  {
    productId: 7,
    warehouseId: 3,
    stock: 0,
    movementId: 7,
    createdAt: now.plus({ seconds: 21 }).toString(),
    updatedAt: now.plus({ seconds: 21 }).toString(),
  },
  {
    productId: 8,
    warehouseId: 1,
    stock: 0,
    movementId: 8,
    createdAt: now.plus({ seconds: 22 }).toString(),
    updatedAt: now.plus({ seconds: 22 }).toString(),
  },
  {
    productId: 8,
    warehouseId: 2,
    stock: 0,
    movementId: 8,
    createdAt: now.plus({ seconds: 23 }).toString(),
    updatedAt: now.plus({ seconds: 23 }).toString(),
  },
  {
    productId: 8,
    warehouseId: 3,
    stock: 0,
    movementId: 8,
    createdAt: now.plus({ seconds: 24 }).toString(),
    updatedAt: now.plus({ seconds: 24 }).toString(),
  },
  {
    productId: 9,
    warehouseId: 1,
    stock: 0,
    movementId: 9,
    createdAt: now.plus({ seconds: 25 }).toString(),
    updatedAt: now.plus({ seconds: 25 }).toString(),
  },
  {
    productId: 9,
    warehouseId: 2,
    stock: 0,
    movementId: 9,
    createdAt: now.plus({ seconds: 26 }).toString(),
    updatedAt: now.plus({ seconds: 26 }).toString(),
  },
  {
    productId: 9,
    warehouseId: 3,
    stock: 0,
    movementId: 9,
    createdAt: now.plus({ seconds: 27 }).toString(),
    updatedAt: now.plus({ seconds: 27 }).toString(),
  },
  {
    productId: 10,
    warehouseId: 1,
    stock: 0,
    movementId: 10,
    createdAt: now.plus({ seconds: 28 }).toString(),
    updatedAt: now.plus({ seconds: 28 }).toString(),
  },
  {
    productId: 10,
    warehouseId: 2,
    stock: 0,
    movementId: 10,
    createdAt: now.plus({ seconds: 29 }).toString(),
    updatedAt: now.plus({ seconds: 29 }).toString(),
  },
  {
    productId: 10,
    warehouseId: 3,
    stock: 0,
    movementId: 10,
    createdAt: now.plus({ seconds: 30 }).toString(),
    updatedAt: now.plus({ seconds: 30 }).toString(),
  },
  {
    productId: 11,
    warehouseId: 1,
    stock: 0,
    movementId: 11,
    createdAt: now.plus({ seconds: 31 }).toString(),
    updatedAt: now.plus({ seconds: 31 }).toString(),
  },
  {
    productId: 11,
    warehouseId: 2,
    stock: 0,
    movementId: 11,
    createdAt: now.plus({ seconds: 32 }).toString(),
    updatedAt: now.plus({ seconds: 32 }).toString(),
  },
  {
    productId: 11,
    warehouseId: 3,
    stock: 0,
    movementId: 11,
    createdAt: now.plus({ seconds: 33 }).toString(),
    updatedAt: now.plus({ seconds: 33 }).toString(),
  },
  {
    productId: 12,
    warehouseId: 1,
    stock: 0,
    movementId: 12,
    createdAt: now.plus({ seconds: 34 }).toString(),
    updatedAt: now.plus({ seconds: 34 }).toString(),
  },
  {
    productId: 12,
    warehouseId: 2,
    stock: 0,
    movementId: 12,
    createdAt: now.plus({ seconds: 35 }).toString(),
    updatedAt: now.plus({ seconds: 35 }).toString(),
  },
  {
    productId: 12,
    warehouseId: 3,
    stock: 0,
    movementId: 12,
    createdAt: now.plus({ seconds: 36 }).toString(),
    updatedAt: now.plus({ seconds: 36 }).toString(),
  },
  /*   {
    productId: 12,
    warehouseId: 3,
    stock: 0,
    movementId: 12,
    createdAt: now.plus({ seconds: 37 }).toString(),
    updatedAt: now.plus({ seconds: 37 }).toString(),
  }, */
  {
    productId: 1,
    warehouseId: 1,
    stock: 40,
    movementId: 13,
    createdAt: now.plus({ seconds: 38 }).toString(),
    updatedAt: now.plus({ seconds: 38 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 12,
    movementId: 13,
    createdAt: now.plus({ seconds: 39 }).toString(),
    updatedAt: now.plus({ seconds: 39 }).toString(),
  },
  {
    productId: 3,
    warehouseId: 1,
    stock: 35,
    movementId: 13,
    createdAt: now.plus({ seconds: 40 }).toString(),
    updatedAt: now.plus({ seconds: 40 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 30,
    movementId: 14,
    createdAt: now.plus({ seconds: 41 }).toString(),
    updatedAt: now.plus({ seconds: 41 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 7,
    movementId: 14,
    createdAt: now.plus({ seconds: 42 }).toString(),
    updatedAt: now.plus({ seconds: 42 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 20,
    movementId: 15,
    createdAt: now.plus({ seconds: 43 }).toString(),
    updatedAt: now.plus({ seconds: 43 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 2,
    movementId: 15,
    createdAt: now.plus({ seconds: 44 }).toString(),
    updatedAt: now.plus({ seconds: 44 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 17,
    movementId: 16,
    createdAt: now.plus({ seconds: 45 }).toString(),
    updatedAt: now.plus({ seconds: 45 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 1,
    stock: 12,
    movementId: 17,
    createdAt: now.plus({ seconds: 46 }).toString(),
    updatedAt: now.plus({ seconds: 46 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 1,
    stock: 1,
    movementId: 17,
    createdAt: now.plus({ seconds: 47 }).toString(),
    updatedAt: now.plus({ seconds: 47 }).toString(),
  },
  {
    productId: 1,
    warehouseId: 2,
    stock: 5,
    movementId: 18,
    createdAt: now.plus({ seconds: 48 }).toString(),
    updatedAt: now.plus({ seconds: 48 }).toString(),
  },
  {
    productId: 2,
    warehouseId: 2,
    stock: 1,
    movementId: 18,
    createdAt: now.plus({ seconds: 49 }).toString(),
    updatedAt: now.plus({ seconds: 49 }).toString(),
  },
];
